version: "3"

services:
  backend:
    image: crowdplay-api-aws
    environment:
      APP_SETTINGS: crowdplay_backend.config.ConfigProd
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      DATABASE_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}/${MYSQL_DATABASE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: crowdplay-ui-aws
    environment:
      NGINX_PORT: 8080
      PROXY_TARGET: http://backend:5000
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:8080
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network:
