name: Code Check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'backend/.flake8'
      - 'backend/requirements.txt'
      - 'backend/crowdplay_backend/**'
      - 'backend/tests/test_*.py'
      - 'frontend/src/**'
      - 'frontend/package.json'
      - 'frontend/.babelrc'
      - 'frontend/.eslintrc'
      - 'frontend/webpack.*'
      - '.github/workflows/**'

jobs:
  check-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx_backend
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-backend-cache
          key: ${{ runner.os }}-buildx-backend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-backend-
      
      # - name: SSH secret key to file
      #   run: |
      #     echo "${{ secrets.SSH_SECRET_KEY }}" > backend/ssh/secret_key

      - name: Build Test Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile.test
          builder: ${{ steps.buildx_backend.outputs.name }}
          push: false
          load: true
          tags: crowdplay-backend-test:latest
          cache-from: type=local,src=/tmp/.buildx-backend-cache
          cache-to: type=local,dest=/tmp/.buildx-backend-cache-new
      
      - name: Lint
        run: |
          docker run crowdplay-backend-test flake8 crowdplay_backend/

      - name: Test
        run: |
          docker run crowdplay-backend-test python -m unittest -v
      
      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-backend-cache
          mv /tmp/.buildx-backend-cache-new /tmp/.buildx-backend-cache

  check-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx_frontend
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-frontend-cache
          key: ${{ runner.os }}-buildx-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-frontend-
      
      - name: Build Test Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.dev
          builder: ${{ steps.buildx_frontend.outputs.name }}
          push: false
          load: true
          tags: crowdplay-frontend-test:latest
          cache-from: type=local,src=/tmp/.buildx-frontend-cache
          cache-to: type=local,dest=/tmp/.buildx-frontend-cache-new
      
      - name: Lint & Test
        run: |
          docker run crowdplay-frontend-test sh -c "npm run lint && npm test"
      
      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-frontend-cache
          mv /tmp/.buildx-frontend-cache-new /tmp/.buildx-frontend-cache